name: Build and Release Windows EXE

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Get version from tag or commit
        id: get_version
        run: |
          echo "##[set-output name=VERSION;]$(git describe --tags --always --dirty)"
        shell: bash

      - name: Restore dependencies
        run: dotnet restore NudgeTimer/NudgeTimer.csproj

      - name: Build and publish self-contained EXE
        run: dotnet publish NudgeTimer/NudgeTimer.csproj -c Release -r win-x64 --self-contained true -p:Version=${{ steps.get_version.outputs.VERSION }} -o publish

      - name: Rename EXE with version
        run: |
          mv publish/NudgeTimer.exe publish/NudgeTimer-${{ steps.get_version.outputs.VERSION }}.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload EXE to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          files: publish/NudgeTimer-${{ steps.get_version.outputs.VERSION }}.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
